package WebsitePlanner.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Indent;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.lang.editor.cellProviders.RefNodeListHandler;
import jetbrains.mps.smodel.action.NodeFactoryManager;
import jetbrains.mps.openapi.editor.menus.transformation.SNodeLocation;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.nodeEditor.cellActions.CellAction_DeleteNode;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.editor.runtime.impl.cellActions.CellAction_DeleteSmart;

/*package*/ class Head_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public Head_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createCollection_4g545y_a();
  }

  private EditorCell createCollection_4g545y_a() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_4g545y_a");
    editorCell.setBig(true);
    editorCell.setCellContext(getCellFactory().getCellContext());
    editorCell.addEditorCell(createConstant_4g545y_a0());
    editorCell.addEditorCell(createConstant_4g545y_b0());
    editorCell.addEditorCell(createProperty_4g545y_c0());
    editorCell.addEditorCell(createConstant_4g545y_d0());
    if (nodeCondition_4g545y_a4a()) {
      editorCell.addEditorCell(createRefNodeList_4g545y_e0());
    }
    if (nodeCondition_4g545y_a5a()) {
      editorCell.addEditorCell(createRefNode_4g545y_f0());
    }
    return editorCell;
  }
  private boolean nodeCondition_4g545y_a4a() {
    return ListSequence.fromList(SLinkOperations.getChildren(myNode, MetaAdapterFactory.getContainmentLink(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L, 0x50c94d2ca8c73690L, "link"))).isNotEmpty();
  }
  private boolean nodeCondition_4g545y_a5a() {
    return (SLinkOperations.getTarget(myNode, MetaAdapterFactory.getContainmentLink(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L, 0x725ca71db780d6e7L, "newLine")) != null);
  }
  private EditorCell createConstant_4g545y_a0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "head");
    editorCell.setCellId("Constant_4g545y_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_4g545y_b0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "title = \"");
    editorCell.setCellId("Constant_4g545y_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_4g545y_c0() {
    CellProviderWithRole provider = new PropertyCellProvider(myNode, getEditorContext());
    provider.setRole("title");
    provider.setNoTargetText("<no title>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(getEditorContext());
    editorCell.setCellId("property_title");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(getEditorContext());
      return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_4g545y_d0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "\"");
    editorCell.setCellId("Constant_4g545y_d0");
    NewLine.setCellActions(editorCell, myNode, getEditorContext());
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNodeList_4g545y_e0() {
    AbstractCellListHandler handler = new Head_EditorBuilder_a.linkListHandler_4g545y_e0(myNode, "link", getEditorContext());
    EditorCell_Collection editorCell = handler.createCells(new CellLayout_Indent(), false);
    editorCell.setCellId("refNodeList_link");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_ON_NEW_LINE, true);
    style.set(StyleAttributes.INDENT_LAYOUT_INDENT, true);
    editorCell.getStyle().putAll(style);
    editorCell.setRole(handler.getElementRole());
    return editorCell;
  }
  private static class linkListHandler_4g545y_e0 extends RefNodeListHandler {
    @NotNull
    private SNode myNode;

    public linkListHandler_4g545y_e0(SNode ownerNode, String childRole, EditorContext context) {
      super(ownerNode, childRole, context, false);
      myNode = ownerNode;
    }

    @Override
    @NotNull
    public SNode getNode() {
      return myNode;
    }

    public SNode createNodeToInsert(EditorContext editorContext) {
      return NodeFactoryManager.createNode(MetaAdapterFactory.getConcept(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c73686L, "WebsitePlanner.structure.Link"), null, getNode(), getNode().getModel());
    }
    public EditorCell createNodeCell(SNode elementNode) {
      EditorCell elementCell = getUpdateSession().updateChildNodeCell(elementNode);
      installElementCellActions(elementNode, elementCell);
      return elementCell;
    }
    public EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(linkListHandler_4g545y_e0.this.getNode(), MetaAdapterFactory.getContainmentLink(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L, 0x50c94d2ca8c73690L, "link")));
      try {
        EditorCell emptyCell = null;
        emptyCell = createConstant_4g545y_a4a();
        installElementCellActions(null, emptyCell);
        setCellContext(emptyCell);
        return emptyCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }
    public void installElementCellActions(SNode elementNode, EditorCell elementCell) {
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
        elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET);
        if (elementNode != null) {
          elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode, CellAction_DeleteNode.DeleteDirection.FORWARD));
          elementCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteNode(elementNode, CellAction_DeleteNode.DeleteDirection.BACKWARD));
        }
        if (elementCell.getSubstituteInfo() == null || elementCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
          elementCell.setSubstituteInfo(new SChildSubstituteInfo(elementCell, getNode(), MetaAdapterFactory.getContainmentLink(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L, 0x50c94d2ca8c73690L, "link"), elementNode));
        }
      }
    }
    private EditorCell createConstant_4g545y_a4a() {
      EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "");
      editorCell.setCellId("Constant_4g545y_a4a");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
  private EditorCell createRefNode_4g545y_f0() {
    SingleRoleCellProvider provider = new Head_EditorBuilder_a.newLineSingleRoleHandler_4g545y_f0(myNode, MetaAdapterFactory.getContainmentLink(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L, 0x725ca71db780d6e7L, "newLine"), getEditorContext());
    return provider.createCell();
  }
  private static class newLineSingleRoleHandler_4g545y_f0 extends SingleRoleCellProvider {
    @NotNull
    private SNode myNode;

    public newLineSingleRoleHandler_4g545y_f0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(containmentLink, context);
      myNode = ownerNode;
    }

    @Override
    @NotNull
    public SNode getNode() {
      return myNode;
    }

    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = getUpdateSession().updateChildNodeCell(child);
      editorCell.setAction(CellActionType.DELETE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L, 0x725ca71db780d6e7L, "newLine"), child));
      editorCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L, 0x725ca71db780d6e7L, "newLine"), child));
      installCellInfo(child, editorCell);
      return editorCell;
    }



    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new SChildSubstituteInfo(editorCell, myNode, MetaAdapterFactory.getContainmentLink(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L, 0x725ca71db780d6e7L, "newLine"), child));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("newLine");
      }
      Style style = new StyleImpl();
      style.set(StyleAttributes.INDENT_LAYOUT_ON_NEW_LINE, true);
      style.set(StyleAttributes.INDENT_LAYOUT_INDENT, true);
      editorCell.getStyle().putAll(style);
    }
    @Override
    protected EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(getNode(), MetaAdapterFactory.getContainmentLink(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L, 0x725ca71db780d6e7L, "newLine")));
      try {
        EditorCell editorCell = super.createEmptyCell();
        editorCell.setCellId("empty_newLine");
        installCellInfo(null, editorCell);
        setCellContext(editorCell);
        return editorCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }
    protected String getNoTargetText() {
      return "<no newLine>";
    }
  }
}
