package WebsitePlanner.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

public class NewLine {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.INSERT, new NewLine.NewLine_INSERT(node));
  }
  public static class NewLine_INSERT extends AbstractCellAction {
    /*package*/ SNode myNode;
    public NewLine_INSERT(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      SLinkOperations.setTarget(node, MetaAdapterFactory.getContainmentLink(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L, 0x725ca71db780d6e7L, "newLine"), SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x725ca71db780d6e6L, "WebsitePlanner.structure.NewLineNode")));
    }
  }
}
