package WebsitePlanner.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class RemoveLink {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.BACKSPACE, new RemoveLink.RemoveLink_BACKSPACE(node));
    editorCell.setAction(CellActionType.INSERT, new RemoveLink.RemoveLink_INSERT(node));
  }
  public static class RemoveLink_BACKSPACE extends AbstractCellAction {
    /*package*/ SNode myNode;
    public RemoveLink_BACKSPACE(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      SNodeOperations.replaceWithAnother(node, null);
    }
  }
  public static class RemoveLink_INSERT extends AbstractCellAction {
    /*package*/ SNode myNode;
    public RemoveLink_INSERT(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      SNodeOperations.replaceWithAnother(node, null);
    }
  }
}
