package WebsitePlanner.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Body = 0;
  public static final int Div = 1;
  public static final int Element = 2;
  public static final int Head = 3;
  public static final int Link = 4;
  public static final int NewLineNode = 5;
  public static final int Reference = 6;
  public static final int Text = 7;
  public static final int Type = 8;
  public static final int Webpage = 9;
  public static final int Website = 10;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL);
    builder.put(0x50c94d2ca8c72383L, Body);
    builder.put(0x50c94d2ca8c73692L, Div);
    builder.put(0x50c94d2ca8c73693L, Element);
    builder.put(0x50c94d2ca8c72382L, Head);
    builder.put(0x50c94d2ca8c73686L, Link);
    builder.put(0x725ca71db780d6e6L, NewLineNode);
    builder.put(0x725ca71db77e4301L, Reference);
    builder.put(0x50c94d2ca8c73696L, Text);
    builder.put(0x725ca71db7881f30L, Type);
    builder.put(0x50c94d2ca8c723bbL, Webpage);
    builder.put(0x50c94d2ca8c72381L, Website);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
