package WebsitePlanner.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBody = createDescriptorForBody();
  /*package*/ final ConceptDescriptor myConceptDiv = createDescriptorForDiv();
  /*package*/ final ConceptDescriptor myConceptElement = createDescriptorForElement();
  /*package*/ final ConceptDescriptor myConceptHead = createDescriptorForHead();
  /*package*/ final ConceptDescriptor myConceptLink = createDescriptorForLink();
  /*package*/ final ConceptDescriptor myConceptNewLineNode = createDescriptorForNewLineNode();
  /*package*/ final ConceptDescriptor myConceptReference = createDescriptorForReference();
  /*package*/ final ConceptDescriptor myConceptText = createDescriptorForText();
  /*package*/ final ConceptDescriptor myConceptType = createDescriptorForType();
  /*package*/ final ConceptDescriptor myConceptWebpage = createDescriptorForWebpage();
  /*package*/ final ConceptDescriptor myConceptWebsite = createDescriptorForWebsite();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBody, myConceptDiv, myConceptElement, myConceptHead, myConceptLink, myConceptNewLineNode, myConceptReference, myConceptText, myConceptType, myConceptWebpage, myConceptWebsite);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.Body:
        return myConceptBody;
      case LanguageConceptSwitch.Div:
        return myConceptDiv;
      case LanguageConceptSwitch.Element:
        return myConceptElement;
      case LanguageConceptSwitch.Head:
        return myConceptHead;
      case LanguageConceptSwitch.Link:
        return myConceptLink;
      case LanguageConceptSwitch.NewLineNode:
        return myConceptNewLineNode;
      case LanguageConceptSwitch.Reference:
        return myConceptReference;
      case LanguageConceptSwitch.Text:
        return myConceptText;
      case LanguageConceptSwitch.Type:
        return myConceptType;
      case LanguageConceptSwitch.Webpage:
        return myConceptWebpage;
      case LanguageConceptSwitch.Website:
        return myConceptWebsite;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForBody() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebsitePlanner", "Body", 0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72383L);
    b.class_(false, false, false);
    b.origin("r:207abca1-ec33-41ba-aaba-d023a703de96(WebsitePlanner.structure)/5821268847558599555");
    b.aggregate("elements", 0x50c94d2ca8c73b51L).target(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c73693L).optional(true).ordered(true).multiple(true).origin("5821268847558605649").done();
    b.alias("body");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDiv() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebsitePlanner", "Div", 0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c73692L);
    b.class_(false, false, false);
    b.parent(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c73693L);
    b.origin("r:207abca1-ec33-41ba-aaba-d023a703de96(WebsitePlanner.structure)/5821268847558604434");
    b.aggregate("contents", 0x50c94d2ca8c73b55L).target(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c73693L).optional(true).ordered(true).multiple(true).origin("5821268847558605653").done();
    b.alias("div");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebsitePlanner", "Element", 0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c73693L);
    b.interface_();
    b.origin("r:207abca1-ec33-41ba-aaba-d023a703de96(WebsitePlanner.structure)/5821268847558604435");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHead() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebsitePlanner", "Head", 0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L);
    b.class_(false, false, false);
    b.origin("r:207abca1-ec33-41ba-aaba-d023a703de96(WebsitePlanner.structure)/5821268847558599554");
    b.prop("title", 0x50c94d2ca8c8f7d6L, "5821268847558719446");
    b.aggregate("link", 0x50c94d2ca8c73690L).target(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c73686L).optional(true).ordered(true).multiple(true).origin("5821268847558604432").done();
    b.aggregate("newLine", 0x725ca71db780d6e7L).target(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x725ca71db780d6e6L).optional(true).ordered(true).multiple(false).origin("8240645164255729383").done();
    b.alias("head");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLink() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebsitePlanner", "Link", 0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c73686L);
    b.class_(false, false, false);
    b.origin("r:207abca1-ec33-41ba-aaba-d023a703de96(WebsitePlanner.structure)/5821268847558604422");
    b.aggregate("href", 0x725ca71db77e441bL).target(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x725ca71db77e4301L).optional(true).ordered(true).multiple(false).origin("8240645164255560731").done();
    b.aggregate("type", 0x725ca71db7881f2bL).target(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x725ca71db7881f30L).optional(true).ordered(true).multiple(false).origin("8240645164256206635").done();
    b.alias("link");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNewLineNode() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebsitePlanner", "NewLineNode", 0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x725ca71db780d6e6L);
    b.class_(false, false, false);
    b.origin("r:207abca1-ec33-41ba-aaba-d023a703de96(WebsitePlanner.structure)/8240645164255729382");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebsitePlanner", "Reference", 0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x725ca71db77e4301L);
    b.class_(false, false, false);
    b.origin("r:207abca1-ec33-41ba-aaba-d023a703de96(WebsitePlanner.structure)/8240645164255560449");
    b.prop("name", 0x725ca71db77e4419L, "8240645164255560729");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebsitePlanner", "Text", 0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c73696L);
    b.class_(false, false, false);
    b.parent(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c73693L);
    b.origin("r:207abca1-ec33-41ba-aaba-d023a703de96(WebsitePlanner.structure)/5821268847558604438");
    b.prop("contents", 0x50c94d2ca8c73b53L, "5821268847558605651");
    b.alias("text");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebsitePlanner", "Type", 0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x725ca71db7881f30L);
    b.class_(false, false, false);
    b.origin("r:207abca1-ec33-41ba-aaba-d023a703de96(WebsitePlanner.structure)/8240645164256206640");
    b.prop("name", 0x725ca71db7881f31L, "8240645164256206641");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWebpage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebsitePlanner", "Webpage", 0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c723bbL);
    b.class_(false, false, true);
    b.origin("r:207abca1-ec33-41ba-aaba-d023a703de96(WebsitePlanner.structure)/5821268847558599611");
    b.aggregate("head", 0x50c94d2ca8c723beL).target(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72382L).optional(true).ordered(true).multiple(false).origin("5821268847558599614").done();
    b.aggregate("body", 0x50c94d2ca8c723c0L).target(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72383L).optional(true).ordered(true).multiple(false).origin("5821268847558599616").done();
    b.alias("html");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWebsite() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("WebsitePlanner", "Website", 0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c72381L);
    b.class_(false, false, true);
    b.origin("r:207abca1-ec33-41ba-aaba-d023a703de96(WebsitePlanner.structure)/5821268847558599553");
    b.prop("name", 0x50c94d2ca8c723dcL, "5821268847558599644");
    b.aggregate("webpages", 0x50c94d2ca8c723bcL).target(0xb05d5b3ef2c14fe3L, 0x803e2c0226d1a19cL, 0x50c94d2ca8c723bbL).optional(true).ordered(true).multiple(true).origin("5821268847558599612").done();
    b.alias("website");
    return b.create();
  }
}
