package HTMLmodel.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int attributeInterface = 0;
  public static final int attributedTextNode = 1;
  public static final int bodyNode = 2;
  public static final int classNode = 3;
  public static final int divNode = 4;
  public static final int elementInterface = 5;
  public static final int headNode = 6;
  public static final int hrefNode = 7;
  public static final int idNode = 8;
  public static final int linkNode = 9;
  public static final int metadataInterface = 10;
  public static final int newlineNode = 11;
  public static final int pNode = 12;
  public static final int relNode = 13;
  public static final int styleNode = 14;
  public static final int textNode = 15;
  public static final int titleNode = 16;
  public static final int typeNode = 17;
  public static final int webpageNode = 18;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x6f2104b7c2144023L, 0xa13f2bec55d0d35aL);
    builder.put(0x69f2237cf23b1066L, attributeInterface);
    builder.put(0x207ab1255de44bcdL, attributedTextNode);
    builder.put(0x69f2237cf23b105fL, bodyNode);
    builder.put(0x69f2237cf23b106eL, classNode);
    builder.put(0x69f2237cf23b106bL, divNode);
    builder.put(0x69f2237cf23b106aL, elementInterface);
    builder.put(0x69f2237cf23b105bL, headNode);
    builder.put(0x69f2237cf23b1068L, hrefNode);
    builder.put(0x69f2237cf23b106fL, idNode);
    builder.put(0x69f2237cf23b1065L, linkNode);
    builder.put(0x69f2237cf23b1060L, metadataInterface);
    builder.put(0x69f2237cf23b1071L, newlineNode);
    builder.put(0x69f2237cf23b106cL, pNode);
    builder.put(0x69f2237cf23b1067L, relNode);
    builder.put(0x69f2237cf23b106dL, styleNode);
    builder.put(0x69f2237cf23b1070L, textNode);
    builder.put(0x69f2237cf23b1061L, titleNode);
    builder.put(0x69f2237cf23b1069L, typeNode);
    builder.put(0x69f2237cf23b0fbeL, webpageNode);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
